[package]
name = "giphybot"
version = "0.1.0"
authors = ["James N. V. Cash <james.nvc@gmail.com>"]

[dependencies]
iron = "^0.3"
rmp = "^0.7"
serde = "^0.7"
serde_macros = "0.7.8"
rmp-serde = "^0.9"
uuid = "0.2"
